name: dono
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_nav_bar: ^5.0.6
  font_awesome_flutter: ^10.1.0
  shared_preferences: ^2.0.15
  provider: ^6.1.2
  http: ^0.13.5
  image_picker: ^1.1.2
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_database: ^10.4.0
  firebase_storage: ^11.6.0
  cloud_firestore: ^4.14.0
  file_picker: ^8.0.6
  carousel_slider: ^4.2.1
  dotted_border: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - img/background.jpg
    - img/logo.png

  fonts:
    - family: Roboto
